package me.kanuunankuulaspluginhead.headHunter.Texture.Enum;

import org.bukkit.Bukkit;
import me.kanuunankuulaspluginhead.headHunter.MainScript;

import java.util.*;
import org.bukkit.profile.PlayerProfile;
import org.bukkit.profile.PlayerTextures;
import java.net.URL;

public enum EntityHeadVariants {
    SNIFFER("SNIFFER", "entity.sniffer.happy",
            "NDNmM2JlMDlhNzM1M2VlYWU5NGQ4ODMyMGNiNWIyNDJkZTJmNzE5YzBlNWMxNmE0ODYzMjdjNjA1ZGIxZDQ2MyJ9fX0="),
    CAMEL("CAMEL", "entity.camel.ambient", 
            "OTJiMzEyMzk1MjA1MTFjYTdiNjcxMmVmMGVjZmI1NWI2YzU2YjkzNDcyNDBmNGNiZjk5MjVjZTBiZjBmYTQ0NSJ9fX0="),
    AXOLOTL_LUCY("AXOLOTL", "entity.axolotl.idle_air", 
            "NWMxMzhmNDAxYzY3ZmMyZTFlMzg3ZDljOTBhOTY5MTc3MmVlNDg2ZThkZGJmMmVkMzc1ZmM4MzQ4NzQ2ZjkzNiJ9fX0="),
    AXOLOTL_WILD("AXOLOTL", "entity.axolotl.idle_air", 
            "NTQ2MWM0ZjJjYjFlZGE4ZTE0Y2Q1OWVmYjBiZjg5ZWEyMDc2ZjU0YTA4YjhiNmQwZGIwYmQwNzk3ZDk5YmVlOCJ9fX0="),
    AXOLOTL_CYAN("AXOLOTL", "entity.axolotl.idle_air", 
            "NWZlMTljNjMxMWVhMDM4NTk2NjY4ZmYwOTFlNDRjZGU0MDk0M2ZmNTcxOGQ1ZjI5ZWI5MGYwMjFhMWI0NThiOSJ9fX0="),
    AXOLOTL_GOLD("AXOLOTL", "entity.axolotl.idle_air", 
            "M2E2NTM0YzMyYWI4NTYwMjg1NTg0NzgxMTVkOTA0ZDUyZjVmMTU0ZDgwZWNiOTAzYjg2NmIxOTA5OWEyNWU0NiJ9fX0="),
    AXOLOTL_BLUE("AXOLOTL", "entity.axolotl.idle_air", 
            "MzU3YjMyYzI5MzNiZWJjZDY1MDJjYmY0MDZmN2RmOTk2YzhlNDZlN2M2Y2JmZWZjNWRjZGMyZmJmNWJiNTRiYiJ9fX0="),
    BAT("BAT", "entity.bat.ambient", 
            "NjY4MWE3MmRhNzI2M2NhOWFlZjA2NjU0MmVjY2E3YTE4MGM0MGUzMjhjMDQ2M2ZjYjExNGNiM2I4MzA1NzU1MiJ9fX0="),
    BEE_AWARE("BEE", "entity.bee.loop_aggressive", 
            "ZDg5MTZlYTFmZmIzOWYxM2RiYmY0ZTYyNDQ5ZGQyY2JkNWQyODEyZjQxNGU5NzYwOGFmMDYwOWUxMzlkNjExNSJ9fX0="),
    BEE("BEE", "entity.bee.loop", 
            "NTE2MmRkMGI5ZjY1YjU4YTFlNzBmODFkOGUwM2U4ZmY2YzUzZTRlOTg1YmRiZTAxODY1NThkOGE2OWE4MTE4OSJ9fX0="),
    BLAZE("BLAZE", "entity.blaze.ambient", 
            "Yjc4ZWYyZTRjZjJjNDFhMmQxNGJmZGU5Y2FmZjEwMjE5ZjViMWJmNWIzNWE0OWViNTFjNjQ2Nzg4MmNiNWYwIn19fQ=="),
    CAT_BLACK("CAT", "entity.cat.ambient", 
            "NGZkMTBjOGU3NWY2NzM5OGM0NzU4N2QyNWZjMTQ2ZjMxMWMwNTNjYzVkMGFlYWI4NzkwYmNlMzZlZTg4ZjVmOCJ9fX0="),
    CAT_ALL_BLACK("CAT", "entity.cat.ambient", 
            "MjJjMWU4MWZmMDNlODJhM2U3MWUwY2Q1ZmJlYzYwN2UxMTM2MTA4OWFhNDdmMjkwZDQ2YzhhMmMwNzQ2MGQ5MiJ9fX0="),
    CAT_BRITISH("CAT", "entity.cat.ambient", 
            "NTM4OWUwZDVkM2U4MWY4NGI1NzBlMjk3ODI0NGIzYTczZTVhMjJiY2RiNjg3NGI0NGVmNWQwZjY2Y2EyNGVlYyJ9fX0="),
    CAT_CALICO("CAT", "entity.cat.ambient", 
            "ZmE4MjRhODdhYWMyMWRkYWFkOGRhMGY0ZDA1MzMzMmE0YjUyOWFiZDNkMThlZGM1Zjg2NzVmZjJhOTViZWM3In19fQ=="),
    CAT_JELLIE("CAT", "entity.cat.ambient", 
            "YTBkYjQxMzc2Y2E1N2RmMTBmY2IxNTM5ZTg2NjU0ZWVjZmQzNmQzZmU3NWU4MTc2ODg1ZTkzMTg1ZGYyODBhNSJ9fX0="),
    CAT_PERSIAN("CAT", "entity.cat.ambient", 
            "ZmY0MGM3NDYyNjBlZjkxYzk2YjI3MTU5Nzk1ZTg3MTkxYWU3Y2UzZDVmNzY3YmY4Yzc0ZmFhZDk2ODlhZjI1ZCJ9fX0="),
    CAT_RAGDOLL("CAT", "entity.cat.ambient", 
            "ZGM3YTQ1ZDI1ODg5ZTNmZGY3Nzk3Y2IyNThlMjZkNGU5NGY1YmMxM2VlZjAwNzk1ZGFmZWYyZTgzZTBhYjUxMSJ9fX0="),
    CAT_RED("CAT", "entity.cat.ambient", 
            "NGI0MzJiN2M4NDY4Y2Y2ODkyODY4ZDg2M2QzOGRkOWU2YjRjYzA1NTU3NjhiOGUwNzEzN2Y4NzhmMzNlNWIifX19"),
    CAT_SIAMESE("CAT", "entity.cat.ambient", 
            "MjlmMTY5OTJmM2E5MmMyZTYyZmQzOGQ1ZDg1MWZkNjYxY2ViM2U4YTgxMDIwMDUzNmVhNGIxMmViMDVmMzQxZSJ9fX0="),
    CAT_TABBY("CAT", "entity.cat.ambient", 
            "ZGUyOGQzMGRiM2Y4YzNmZTUwY2E0ZjI2ZjMwNzVlMzZmMDAzYWU4MDI4MTM1YThjZDY5MmYyNGM5YTk4YWUxYiJ9fX0="),
    CAT_WHITE("CAT", "entity.cat.ambient", 
            "OTZmMTQ5Njg0NDUzYTIwZjRmYjU3YmUxNTc1YjMwOTFjYzA5YzNlNDBhZGE4OWM2ZmNhYzhhNWEwZWM3N2M1YiJ9fX0="),
    CAVE_SPIDER("CAVE_SPIDER", "entity.spider.ambient", 
            "NTYxN2Y3ZGQ1ZWQxNmYzYmQxODY0NDA1MTdjZDQ0MGExNzAwMTViMWNjNmZjYjJlOTkzYzA1ZGUzM2YifX19"),
    CHICKEN_TEMPERATE("CHICKEN", "entity.chicken.ambient", 
            "Y2EzNTgyY2U0ODg5MzMzZGFkMzI5ZTRlMjQzNzJhMDNhNWRhYTJjMzQyODBjNTYyNTZhZjUyODNlZGIwNDNmOCJ9fX0="),
    CHICKEN_COLD("CHICKEN", "entity.chicken.ambient", 
            "YTkxMWZjZDhiMjI2YTk4ZjhiNmQ2MDVmZjI3YTg4ZWQ5NzIzMGJiNzE2NzhlNGEwMDY2OTA5NWQ2OWQzZjJiNCJ9fX0="),
    CHICKEN_WARM("CHICKEN", "entity.chicken.ambient", 
            "NThjMjMxYmY0NjRmOWE2YzY3ODZhMjJhNGQxMTllYTVlNTA1NzYyNGM1YTM5MTQ3MGQzNWZhMmI2ZmZhNTE4MyJ9fX0="),
    COD("COD", "entity.cod.flop", 
            "Nzg5MmQ3ZGQ2YWFkZjM1Zjg2ZGEyN2ZiNjNkYTRlZGRhMjExZGY5NmQyODI5ZjY5MTQ2MmE0ZmIxY2FiMCJ9fX0="),
    COW_TEMPERATE("COW", "entity.cow.ambient", 
            "N2RmYTBhYzM3YmFiYTJhYTI5MGU0ZmFlZTQxOWE2MTNjZDYxMTdmYTU2OGU3MDlkOTAzNzQ3NTNjMDMyZGNiMCJ9fX0="),
    COW_COLD("COW", "entity.cow.ambient", 
            "NGJmNjgyZmExZWNiNjMzZDgzZTE2NGIzODA1OWYxYzU4NDgwZmFlNWNlZWFhODdjOTM0OGMyOWUwYTEyMTU3OCJ9fX0="),
    COW_WARM("COW", "entity.cow.ambient", 
            "MzdlZWI0OTMzNWUwM2ZlNzkxMTI5NTA3NWQ2YWUxZThhOWIwOTFmYzZjNDg5NmZkMmNjZWM4MzU5YzEwYjAwNiJ9fX0="),
    DOLPHIN("DOLPHIN", "entity.dolphin.ambient", 
            "OGU5Njg4Yjk1MGQ4ODBiNTViN2FhMmNmY2Q3NmU1YTBmYTk0YWFjNmQxNmY3OGU4MzNmNzQ0M2VhMjlmZWQzIn19fQ=="),
    DONKEY("DONKEY", "entity.donkey.ambient", 
            "ZGZiNmMzYzA1MmNmNzg3ZDIzNmEyOTE1ZjgwNzJiNzdjNTQ3NDk3NzE1ZDFkMmY4Y2JjOWQyNDFkODhhIn19fQ=="),
    DROWNED("DROWNED", "entity.drowned.ambient", 
            "Yzg0ZGY3OWM0OTEwNGIxOThjZGFkNmQ5OWZkMGQwYmNmMTUzMWM5MmQ0YWI2MjY5ZTQwYjdkM2NiYmI4ZTk4YyJ9fX0="),
    ELDER_GUARDIAN("ELDER_GUARDIAN", "entity.elder_guardian.ambient", 
            "ZTkyMDg5NjE4NDM1YTBlZjYzZTk1ZWU5NWE5MmI4MzA3M2Y4YzMzZmE3N2RjNTM2NTE5OWJhZDMzYjYyNTYifX19"),
    ENDERMAN("ENDERMAN", "entity.enderman.ambient", 
            "OTZjMGIzNmQ1M2ZmZjY5YTQ5YzdkNmYzOTMyZjJiMGZlOTQ4ZTAzMjIyNmQ1ZTgwNDVlYzU4NDA4YTM2ZTk1MSJ9fX0="),
    ENDERMITE("ENDERMITE", "entity.endermite.ambient", 
            "NWJjN2I5ZDM2ZmI5MmI2YmYyOTJiZTczZDMyYzZjNWIwZWNjMjViNDQzMjNhNTQxZmFlMWYxZTY3ZTM5M2EzZSJ9fX0="),
    EVOKER("EVOKER", "entity.evoker.ambient", 
            "ZDk1NDEzNWRjODIyMTM5NzhkYjQ3ODc3OGFlMTIxMzU5MWI5M2QyMjhkMzZkZDU0ZjFlYTFkYTQ4ZTdjYmE2In19fQ=="),
    FOX("FOX", "entity.fox.ambient", 
            "ZDg5NTRhNDJlNjllMDg4MWFlNmQyNGQ0MjgxNDU5YzE0NGEwZDVhOTY4YWVkMzVkNmQzZDczYTNjNjVkMjZhIn19fQ=="),
    FOX_WHITE("FOX", "entity.fox.ambient", 
            "NDE0MzYzNzdlYjRjNGI0ZTM5ZmIwZTFlZDg4OTlmYjYxZWUxODE0YTkxNjliOGQwODcyOWVmMDFkYzg1ZDFiYSJ9fX0="),
    GIANT("GIANT", "entity.zombie.ambient", 
            "NTZmYzg1NGJiODRjZjRiNzY5NzI5Nzk3M2UwMmI3OWJjMTA2OTg0NjBiNTFhNjM5YzYwZTVlNDE3NzM0ZTExIn19fQ=="),
    GLOW_SQUID("GLOW_SQUID", "entity.glow_squid.ambient", 
            "MmVjZDBiNWViNmIzODRkYjA3NmQ4NDQ2MDY1MjAyOTU5ZGRkZmYwMTYxZTBkNzIzYjNkZjBjYzU4NmQxNmJiZCJ9fX0="),
    GOAT("GOAT", "entity.goat.ambient", 
            "ZjAzMzMwMzk4YTBkODMzZjUzYWU4YzlhMWNiMzkzYzc0ZTlkMzFlMTg4ODU4NzBlODZhMjEzM2Q0NGYwYzYzYyJ9fX0="),
    GUARDIAN("GUARDIAN", "entity.guardian.ambient", 
            "YTBiZjM0YTcxZTc3MTViNmJhNTJkNWRkMWJhZTVjYjg1Zjc3M2RjOWIwZDQ1N2I0YmZjNWY5ZGQzY2M3Yzk0In19fQ=="),
    HOGLIN("HOGLIN", "entity.hoglin.ambient", 
            "OWJiOWJjMGYwMWRiZDc2MmEwOGQ5ZTc3YzA4MDY5ZWQ3Yzk1MzY0YWEzMGNhMTA3MjIwODU2MWI3MzBlOGQ3NSJ9fX0="),
    HORSE_WHITE("HORSE", "entity.horse.ambient", 
            "OGIwM2ViMTNkNzk4ZjM4MjM3MDMzNTdhYTZlOGZkMjlkZmYzMDEwODcxYjRlNTRmOTI4ZTI3MGQ3NDEwOTY5YiJ9fX0="),
    HORSE_CREAMY("HORSE", "entity.horse.ambient", 
            "YTZkYWUwYWRlMGUwZGFmYjZkYmM3Nzg2Y2U0MjQxMjQyYjZiNmRmNTI3YTBmN2FmMGE0MjE4NGM5M2ZkNjQ2YiJ9fX0="),
    HORSE_CHESTNUT("HORSE", "entity.horse.ambient", 
            "OTcxN2Q3MTAyNWY3YTYyYzkwYTMzM2M1MTY2M2ZmZWIzODVhOWEwZDkyYWY2ODA4M2M1YjA0NWMwNTI0YjIzZiJ9fX0="),
    HORSE_BROWN("HORSE", "entity.horse.ambient", 
            "MjVlMzk3ZGVmMGFmMDZmZWVmMjI0MjE4NjAwODgxODY2Mzk3MzJhYTBhNWViNTc1NmUwYWE2YjAzZmQwOTJjOCJ9fX0="),
    HORSE_BLACK("HORSE", "entity.horse.ambient", 
            "M2VmYjBiOTg1N2Q3YzhkMjk1ZjZkZjk3YjYwNWY0MGI5ZDA3ZWJlMTI4YTY3ODNkMWZhM2UxYmM2ZTQ0MTE3In19fQ=="),
    HORSE_GRAY("HORSE", "entity.horse.ambient", 
            "OGYwZDk1NTg4OWIwMzc4ZDQ5MzNjOTU2Mzk4NTY3ZTc3MDEwM2FlOWVmZjBmNzAyZDBkNTNkNTJlN2Y2YTgzYiJ9fX0="),
    HORSE_DARK_BROWN("HORSE", "entity.horse.ambient", 
            "MTU2YjdiYzFhNDgzNmViNDI4ZWE4OTI1ZWNlYjVlMDFkZmJkMzBjN2RlZmY2Yzk0ODI2ODk4MjMyMDNjZmQyZiJ9fX0="),
    HUSK("HUSK", "entity.husk.ambient", 
            "MjY5Yjk3MzRkMGU3YmYwNjBmZWRjNmJmN2ZlYzY0ZTFmN2FkNmZjODBiMGZkODQ0MWFkMGM3NTA4Yzg1MGQ3MyJ9fX0="),
    ILLUSIONER("ILLUSIONER", "entity.illusioner.ambient", 
            "NTEyNTEyZTdkMDE2YTIzNDNhN2JmZjFhNGNkMTUzNTdhYjg1MTU3OWYxMzg5YmQ0ZTNhMjRjYmViODhiIn19fQ=="),
    IRON_GOLEM("IRON_GOLEM", "entity.iron_golem.step", 
            "ODkwOTFkNzllYTBmNTllZjdlZjk0ZDdiYmE2ZTVmMTdmMmY3ZDQ1NzJjNDRmOTBmNzZjNDgxOWE3MTQifX19"),
    LLAMA_BROWN("LLAMA", "entity.llama.ambient", 
            "YzJiMWVjZmY3N2ZmZTNiNTAzYzMwYTU0OGViMjNhMWEwOGZhMjZmZDY3Y2RmZjM4OTg1NWQ3NDkyMTM2OCJ9fX0="),
    LLAMA_GRAY("LLAMA", "entity.llama.ambient", 
            "Y2YyNGU1NmZkOWZmZDcxMzNkYTZkMWYzZTJmNDU1OTUyYjFkYTQ2MjY4NmY3NTNjNTk3ZWU4MjI5OWEifX19"),
    LLAMA_CREAMY("LLAMA", "entity.llama.ambient", 
            "MmE1ZjEwZTZlNjIzMmYxODJmZTk2NmY1MDFmMWMzNzk5ZDQ1YWUxOTAzMWExZTQ5NDFiNWRlZTBmZWZmMDU5YiJ9fX0="),
    LLAMA_WHITE("LLAMA", "entity.llama.ambient", 
            "ODNkOWI1OTE1OTEyZmZjMmI4NTc2MWQ2YWRjYjQyOGE4MTJmOWI4M2ZmNjM0ZTMzMTE2MmNlNDZjOTllOSJ9fX0="),
    MAGMA_CUBE("MAGMA_CUBE", "entity.magma_cube.squish", 
            "Mzg5NTdkNTAyM2M5MzdjNGM0MWFhMjQxMmQ0MzQxMGJkYTIzY2Y3OWE5ZjZhYjM2Yjc2ZmVmMmQ3YzQyOSJ9fX0="),
    MULE("MULE", "entity.mule.ambient", 
            "NDZkY2RhMjY1ZTU3ZTRmNTFiMTQ1YWFjYmY1YjU5YmRjNjA5OWZmZDNjY2UwYTY2MWIyYzAwNjVkODA5MzBkOCJ9fX0="),
    MOOSHROOM_COW_BROWN("MOOSHROOM", "entity.cow.ambient", 
            "YjZkNWZjNzAzMWFjYzk1YmVlYjUyODc1ZjE1NDA4ZTk3OWEwYTljMzkxYjZkYjdlY2VlN2U0MDAwNzJkZTVjNCJ9fX0="),
    MOOSHROOM_COW_RED("MOOSHROOM", "entity.cow.ambient", 
            "MmI1Mjg0MWYyZmQ1ODllMGJjODRjYmFiZjllMWMyN2NiNzBjYWM5OGY4ZDZiM2RkMDY1ZTU1YTRkY2I3MGQ3NyJ9fX0="),
    OCELOT("OCELOT", "entity.ocelot.ambient", 
            "NTY1N2NkNWMyOTg5ZmY5NzU3MGZlYzRkZGNkYzY5MjZhNjhhMzM5MzI1MGMxYmUxZjBiMTE0YTFkYjEifX19"),
    PANDA("PANDA", "entity.panda.ambient", 
            "ODAxOGExNzcxZDY5YzExYjhkYWQ0MmNkMzEwMzc1YmEyZDgyNzkzMmIyNWVmMzU3ZjdlNTcyYzFiZDBmOSJ9fX0="),
    PANDA_BROWN("PANDA", "entity.panda.ambient", 
            "YzVkMGQ0NWJmOTkyYjA3MmNmNWM1MTNlMDZiZWVmZThiZGM4MDljODE1MGYzZDE0Yjg4Mzc5NmE3Yjc0ZTQwNiJ9fX0="),
    PHANTOM("PHANTOM", "entity.phantom.ambient", 
            "N2U5NTE1M2VjMjMyODRiMjgzZjAwZDE5ZDI5NzU2ZjI0NDMxM2EwNjFiNzBhYzAzYjk3ZDIzNmVlNTdiZDk4MiJ9fX0="),
    PIG_TEMPERATE("PIG", "entity.pig.ambient", 
            "YmVlODUxNDg5MmYzZDc4YTMyZTg0NTZmY2JiOGM2MDgxZTIxYjI0NmQ4MmYzOThiZDk2OWZlYzE5ZDNjMjdiMyJ9fX0="),
    PIG_COLD("PIG", "entity.pig.ambient", 
            "YmExOGQ0MDQzY2Q2YzkwMzg2Njc4ODkxNGZkNTM0MzE1MjgxYWY5ZjI1OWUzNDgzN2UzZTE3NWU1NDVjMmVkZSJ9fX0="),
    PIG_WARM("PIG", "entity.pig.ambient", 
            "N2JlYmExYTJkNTZlODRmOGU1MWZlZDY2NTlmMmNiN2MxNGZlZDQzODU5YWY1ODQ3Mzc4OTdiZjcwYzAzOTQ3NSJ9fX0="),
    PIGLIN("PIGLIN", "entity.piglin.ambient", 
            "OWYxODEwN2QyNzVmMWNiM2E5Zjk3M2U1OTI4ZDU4NzlmYTQwMzI4ZmYzMjU4MDU0ZGI2ZGQzZTdjMGNhNjMzMCJ9fX0="),
    PIGLIN_BRUTE("PIGLIN_BRUTE", "entity.piglin_brute.ambient", 
            "M2UzMDBlOTAyNzM0OWM0OTA3NDk3NDM4YmFjMjllM2E0Yzg3YTg0OGM1MGIzNGMyMTI0MjcyN2I1N2Y0ZTFjZiJ9fX0="),
    PILLAGER("PILLAGER", "entity.pillager.ambient", 
            "NGFlZTZiYjM3Y2JmYzkyYjBkODZkYjVhZGE0NzkwYzY0ZmY0NDY4ZDY4Yjg0OTQyZmRlMDQ0MDVlOGVmNTMzMyJ9fX0="),
    POLAR_BEAR("POLAR_BEAR", "entity.polar_bear.ambient", 
            "Y2Q1ZDYwYTRkNzBlYzEzNmE2NTg1MDdjZTgyZTM0NDNjZGFhMzk1OGQ3ZmNhM2Q5Mzc2NTE3YzdkYjRlNjk1ZCJ9fX0="),
    PUFFERFISH("PUFFERFISH", "entity.puffer_fish.ambient", 
            "MTcxNTI4NzZiYzNhOTZkZDJhMjI5OTI0NWVkYjNiZWVmNjQ3YzhhNTZhYzg4NTNhNjg3YzNlN2I1ZDhiYiJ9fX0="),
    RABBIT_BROWN("RABBIT", "entity.rabbit.hurt", 
            "YzFkYjM4ZWYzYzFhMWQ1OWY3NzlhMGNkOWY5ZTYxNmRlMGNjOWFjYzc3MzRiOGZhY2MzNmZjNGVhNDBkMDIzNSJ9fX0="),
    RABBIT_WHITE("RABBIT", "entity.rabbit.hurt", 
            "YTBkY2RkYzIzNjk3MmVkY2Q0OGU4MjViNmIwMDU0YjdiNmUxYTc4MWU2ZjEyYWUwNGMxNGEwNzgyN2NhOGRjYyJ9fX0="),
    RABBIT_BLACK("RABBIT", "entity.rabbit.hurt", 
            "MTlhNjc1ZWRiM2NiYTBmMzQzNmFlOTQ3M2NmMDM1OTJiN2E0OWQzODgxMzU3OTA4NGQ2MzdlNzY1OTk5OWI4ZSJ9fX0="),
    RABBIT_BLACK_AND_WHITE("RABBIT", "entity.rabbit.hurt", 
            "MzJmMzllMGE2MDMzODZjYTFlZTM2MjM2ZTBiNDkwYTE1NDdlNmUyYTg5OTExNjc0NTA5MDM3ZmI2ZjcxMTgxMCJ9fX0="),
    RABBIT_GOLD("RABBIT", "entity.rabbit.hurt", 
            "MmE2MzYxZmVhMjRiMTExZWQ3OGMxZmVmYzI5NTIxMmU4YTU5YjBjODhiNjU2MDYyNTI3YjE3YTJkNzQ4OWM4MSJ9fX0="),
    RABBIT_SALT_AND_PEPPER("RABBIT", "entity.rabbit.hurt", 
            "Y2M0MzQ5ZmU5OTAyZGQ3NmMxMzYxZjhkNmExZjc5YmZmNmY0MzNmM2I3YjE4YTQ3MDU4ZjBhYTE2YjkwNTNmIn19fQ=="),
    RABBIT_THE_KILLER_BUNNY("RABBIT", "entity.rabbit.hurt", 
            "ZWY5ODMzN2I4MjQyMjI5ZDk1ZGEyMzA5MDc1NTc4OTc3OGIxOGJmNWQwN2Q2MWY2MjBjZGJkYmJkMjlmYTYxNSJ9fX0="),
    RAVAGER("RAVAGER", "entity.ravager.ambient", 
            "Y2QyMGJmNTJlYzM5MGEwNzk5Mjk5MTg0ZmM2NzhiZjg0Y2Y3MzJiYjFiZDc4ZmQxYzRiNDQxODU4ZjAyMzVhOCJ9fX0="),
    SALMON("SALMON", "entity.salmon.ambient", 
            "OGFlYjIxYTI1ZTQ2ODA2Y2U4NTM3ZmJkNjY2ODI4MWNmMTc2Y2VhZmU5NWFmOTBlOTRhNWZkODQ5MjQ4NzgifX19"),
    SHEEP_WHITE("SHEEP", "entity.sheep.ambient", 
            "ZjMxZjljY2M2YjNlMzJlY2YxM2I4YTExYWMyOWNkMzNkMThjOTVmYzczZGI4YTY2YzVkNjU3Y2NiOGJlNzAifX19"),
    SHEEP_BLACK("SHEEP", "entity.sheep.ambient", 
            "MzI2NTIwODNmMjhlZDFiNjFmOWI5NjVkZjFhYmYwMTBmMjM0NjgxYzIxNDM1OTUxYzY3ZDg4MzY0NzQ5ODIyIn19fQ=="),
    SHEEP_PURPLE("SHEEP", "entity.sheep.ambient", 
            "YWU1Mjg2N2FmZWYzOGJiMTRhMjZkMTQyNmM4YzBmMTE2YWQzNDc2MWFjZDkyZTdhYWUyYzgxOWEwZDU1Yjg1In19fQ=="),
    SHEEP_PINK("SHEEP", "entity.sheep.ambient", 
            "MmFjNzRhMmI5YjkxNDUyZTU2ZmExZGRhNWRiODEwNzc4NTZlNDlmMjdjNmUyZGUxZTg0MWU1Yzk1YTZmYzVhYiJ9fX0="),
    SHEEP_ORANGE("SHEEP", "entity.sheep.ambient", 
            "ZjA5ODM5N2EyNzBiNGMzZDJiMWU1NzRiOGNmZDNjYzRlYTM0MDkwNjZjZWZlMzFlYTk5MzYzM2M5ZDU3NiJ9fX0="),
    SHEEP_MAGENTA("SHEEP", "entity.sheep.ambient", 
            "MTgzNjU2NWM3ODk3ZDQ5YTcxYmMxODk4NmQxZWE2NTYxMzIxYTBiYmY3MTFkNDFhNTZjZTNiYjJjMjE3ZTdhIn19fQ=="),
    SHEEP_LIME("SHEEP", "entity.sheep.ambient", 
            "OTJhMjQ0OGY1OGE0OTEzMzI0MzRlODVjNDVkNzg2ZDg3NDM5N2U4MzBhM2E3ODk0ZTZkOTI2OTljNDJiMzAifX19"),
    SHEEP_LIGHT_GRAY("SHEEP", "entity.sheep.ambient", 
            "Y2UxYWM2ODM5OTNiZTM1NTEyZTFiZTMxZDFmNGY5OGU1ODNlZGIxNjU4YTllMjExOTJjOWIyM2I1Y2NjZGMzIn19fQ=="),
    SHEEP_LIGHT_BLUE("SHEEP", "entity.sheep.ambient", 
            "MWM4YTk3YTM4ODU2NTE0YTE2NDEzZTJjOTk1MjEyODlmNGM1MzYzZGM4MmZjOWIyODM0Y2ZlZGFjNzhiODkifX19"),
    SHEEP_GREEN("SHEEP", "entity.sheep.ambient", 
            "NmRlNTVhMzk1YTIyNDY0NDViNDVmOWE2ZDY4ODcyMzQ0YmJlYTU0ZjM2MmQ1MjlmYzViMGI4NTdlYTU4MzI2YiJ9fX0="),
    SHEEP_GRAY("SHEEP", "entity.sheep.ambient", 
            "NDI4N2ViNTAxMzkxZjI3NTM4OWYxNjZlYzlmZWJlYTc1ZWM0YWU5NTFiODhiMzhjYWU4N2RmN2UyNGY0YyJ9fX0="),
    SHEEP_CYAN("SHEEP", "entity.sheep.ambient", 
            "NDZmNmM3ZTdmZDUxNGNlMGFjYzY4NTkzMjI5ZTQwZmNjNDM1MmI4NDE2NDZlNGYwZWJjY2NiMGNlMjNkMTYifX19"),
    SHEEP_BLUE("SHEEP", "entity.sheep.ambient", 
            "ZDllYzIyODE4ZDFmYmZjODE2N2ZiZTM2NzI4YjI4MjQwZTM0ZTE2NDY5YTI5MjlkMDNmZGY1MTFiZjJjYTEifX19"),
    SHEEP_BROWN("SHEEP", "entity.sheep.ambient", 
            "YTU1YWQ2ZTVkYjU2OTJkODdmNTE1MTFmNGUwOWIzOWZmOWNjYjNkZTdiNDgxOWE3Mzc4ZmNlODU1M2I4In19fQ=="),
    SHEEP_RED("SHEEP", "entity.sheep.ambient", 
            "ODM5YWY0NzdlYjYyNzgxNWY3MjNhNTY2MjU1NmVjOWRmY2JhYjVkNDk0ZDMzOGJkMjE0MjMyZjIzZTQ0NiJ9fX0="),
    SHEEP_YELLOW("SHEEP", "entity.sheep.ambient", 
            "MjZhNDExMmRmMWU0YmNlMmE1ZTI4NDE3ZjNhYWZmNzljZDY2ZTg4NWMzNzI0NTU0MTAyY2VmOGViOCJ9fX0="),
    SHULKER("SHULKER", "entity.shulker.ambient", 
            "MTQzM2E0YjczMjczYTY0YzhhYjI4MzBiMGZmZjc3N2E2MWE0ODhjOTJmNjBmODNiZmIzZTQyMWY0MjhhNDQifX19"),
    SILVERFISH("SILVERFISH", "entity.silverfish.ambient", 
            "ZGE5MWRhYjgzOTFhZjVmZGE1NGFjZDJjMGIxOGZiZDgxOWI4NjVlMWE4ZjFkNjIzODEzZmE3NjFlOTI0NTQwIn19fQ=="),
    SKELETON_HORSE("SKELETON_HORSE", "entity.skeleton_horse.ambient", 
            "NDdlZmZjZTM1MTMyYzg2ZmY3MmJjYWU3N2RmYmIxZDIyNTg3ZTk0ZGYzY2JjMjU3MGVkMTdjZjg5NzNhIn19fQ=="),
    SLIME("SLIME", "entity.slime.jump", 
            "ODk1YWVlYzZiODQyYWRhODY2OWY4NDZkNjViYzQ5NzYyNTk3ODI0YWI5NDRmMjJmNDViZjNiYmI5NDFhYmU2YyJ9fX0="),
    SNOWMAN("SNOW_GOLEM", "entity.snow_golem.ambient", 
            "MWZkZmQxZjc1MzhjMDQwMjU4YmU3YTkxNDQ2ZGE4OWVkODQ1Y2M1ZWY3MjhlYjVlNjkwNTQzMzc4ZmNmNCJ9fX0="),
    SPIDER("SPIDER", "entity.spider.ambient", 
            "Yzg3YTk2YThjMjNiODNiMzJhNzNkZjA1MWY2Yjg0YzJlZjI0ZDI1YmE0MTkwZGJlNzRmMTExMzg2MjliNWFlZiJ9fX0="),
    SQUID("SQUID", "entity.squid.ambient", 
            "ZDg3MDU2MjRkYWEyOTU2YWE0NTk1NmM4MWJhYjVmNGZkYjJjNzRhNTk2MDUxZTI0MTkyMDM5YWVhM2E4YjgifX19"),
    STRAY("STRAY", "entity.stray.ambient", 
            "MmM1MDk3OTE2YmMwNTY1ZDMwNjAxYzBlZWJmZWIyODcyNzdhMzRlODY3YjRlYTQzYzYzODE5ZDUzZTg5ZWRlNyJ9fX0="),
    STRIDER("STRIDER", "entity.strider.ambient", 
            "MTI1ODUxYTg2ZWUxYzU0Yzk0ZmM1YmVkMDE3ODIzZGZiM2JhMDhlZGRiY2FiMmE5MTRlZjQ1YjU5NmMxNjAzIn19fQ=="),
    STRIDER_SHIVERING("STRIDER", "entity.strider.ambient", 
            "YzczODYxMGUyZjczYjY3ZTViYzEyZWJjYmI2ZGRjNDU2MWMyNjViOWQ1YTE3ZDIwZGFlNDkzYTgyNTBkNzAwYiJ9fX0="),
    TRADER_LLAMA_BROWN("TRADER_LLAMA", "entity.llama.ambient", 
            "ODQyNDc4MGIzYzVjNTM1MWNmNDlmYjViZjQxZmNiMjg5NDkxZGY2YzQzMDY4M2M4NGQ3ODQ2MTg4ZGI0Zjg0ZCJ9fX0="),
    TRADER_LLAMA_GRAY("TRADER_LLAMA", "entity.llama.ambient", 
            "YmU0ZDhhMGJjMTVmMjM5OTIxZWZkOGJlMzQ4MGJhNzdhOThlZTdkOWNlMDA3MjhjMGQ3MzNmMGEyZDYxNGQxNiJ9fX0="),
    TRADER_LLAMA_CREAMY("TRADER_LLAMA", "entity.llama.ambient", 
            "ZTg5YTJlYjE3NzA1ZmU3MTU0YWIwNDFlNWM3NmEwOGQ0MTU0NmEzMWJhMjBlYTMwNjBlM2VjOGVkYzEwNDEyYyJ9fX0="),
    TRADER_LLAMA_WHITE("TRADER_LLAMA", "entity.llama.ambient", 
            "NzA4N2E1NTZkNGZmYTk1ZWNkMjg0NGYzNTBkYzQzZTI1NGU1ZDUzNWZhNTk2ZjU0MGQ3ZTc3ZmE2N2RmNDY5NiJ9fX0="),
    TURTLE("TURTLE", "entity.turtle.ambient_land", 
            "MGE0MDUwZTdhYWNjNDUzOTIwMjY1OGZkYzMzOWRkMTgyZDdlMzIyZjlmYmNjNGQ1Zjk5YjU3MThhIn19fQ=="),
    VEX("VEX", "entity.vex.ambient", 
            "YzJlYzVhNTE2NjE3ZmYxNTczY2QyZjlkNWYzOTY5ZjU2ZDU1NzVjNGZmNGVmZWZhYmQyYTE4ZGM3YWI5OGNkIn19fQ=="),
    VEX_CHARGE("VEX", "entity.vex.charge", 
            "OTY4ODZjYjk0ZjNiMzgyY2JjMzIxYWI0NjUzNTgxZjI4MmNhMDg0MTcyOGE0NzhlZTlkNDFhOGEzMjI0NzQzIn19fQ=="),
    VINDICATOR("VINDICATOR", "entity.vindicator.ambient", 
            "NmRlYWVjMzQ0YWIwOTViNDhjZWFkNzUyN2Y3ZGVlNjFiMDYzZmY3OTFmNzZhOGZhNzY2NDJjODY3NmUyMTczIn19fQ=="),
    WANDERING_TRADER("WANDERING_TRADER", "entity.wandering_trader.ambient", 
            "NWYxMzc5YTgyMjkwZDdhYmUxZWZhYWJiYzcwNzEwZmYyZWMwMmRkMzRhZGUzODZiYzAwYzkzMGM0NjFjZjkzMiJ9fX0="),
    WITCH("WITCH", "entity.witch.ambient", 
            "MjBlMTNkMTg0NzRmYzk0ZWQ1NWFlYjcwNjk1NjZlNDY4N2Q3NzNkYWMxNmY0YzNmODcyMmZjOTViZjlmMmRmYSJ9fX0="),
    WITHER("WITHER", "entity.wither.ambient", 
            "Y2RmNzRlMzIzZWQ0MTQzNjk2NWY1YzU3ZGRmMjgxNWQ1MzMyZmU5OTllNjhmYmI5ZDZjZjVjOGJkNDEzOWYifX19"),
    WOLF_ASHEN("WOLF", "entity.wolf.ambient", 
            "MTdkZGM1MWZhZWJkYThhOGU5MTAxYTkwMGUxYWVmMzM3ODE5YThkMGUzZTkxNTY2MGY2ZjM3ZGY5YTM5OGE0OSJ9fX0="),
    WOLF_ASHEN_ANGRY("WOLF", "entity.wolf.ambient", 
            "YjFiYTQ5ODUzYTA0YzZmZGIwMTJiN2E3OWEwZjczODNjZDgyMTg0ZDY3MTE3OTE1MmIwZmU5OTI4MDdjMjY0MSJ9fX0="),
    WOLF_BLACK("WOLF", "entity.wolf.ambient", 
            "ZjA0NWYyZDQ3YmE1YzQ0YzA2MmRlZjcyNWQ0YTRmOTZlNTc0M2Y4MDJkMWZiNGRjZTliNDI3ZGU5NDc1MjBiMyJ9fX0="),
    WOLF_BLACK_ANGRY("WOLF", "entity.wolf.ambient", 
            "Yjg2YjAxMTkyMmYyMGRmMmJiMzAyNzMzNmM0ZDgyN2Q0NjY3NjFkY2VmNTBiN2U3NzMwZmE1Nzc0OWM1NWI2NCJ9fX0="),
    WOLF_CHESTNUT("WOLF", "entity.wolf.ambient", 
            "OWY3MTg5N2E2MTgyYjEwMTY2MGFiMjQzOGU0NTBmNTdjZGFkMmIwOGMyMWI0MDU2NzQ5NTU2MTg1YTRlZjg0ZiJ9fX0="),
    WOLF_CHESTNUT_ANGRY("WOLF", "entity.wolf.ambient", 
            "YzVkYzU5OWJmNzJjMTFlNzA5MTlmMzc0OGIxY2RkYjg1ZTBkZDJhZDA5OWMyY2U1YTVlMmY0NzY3NjBkOTBlMCJ9fX0="),
    WOLF_PALE("WOLF", "entity.wolf.ambient", 
            "OGYwYjIyMTc4NmYxOTNjMDZkZDE5YTc4NzVhOTAzNjM1MTEzZjg0NTIzOTI3YmI2OTc2NDIzN2ZlMjA3MDNkZSJ9fX0="),
    WOLF_PALE_ANGRY("WOLF", "entity.wolf.ambient", 
            "MWFhODQ2MTFjOGM4OTU4MzM2ZjY0ZDU4ZGMyMDljN2FiOTU4ZGRkOTlkMmY1ODc2ZGFkNzI2M2Y3MGVjZWIyNyJ9fX0="),
    WOLF_RUSTY("WOLF", "entity.wolf.ambient", 
            "NjcwZWVjZWE3OGZjYzg3ZjgwZTgxMjU3MzM0MjNjOTZhODhiYjYwNDA4YzcwMjVkZDU0OTk4ZDYyOWJlZTUxNCJ9fX0="),
    WOLF_RUSTY_ANGRY("WOLF", "entity.wolf.ambient", 
            "ZjA2NmNlZmRhODAzNTQzYjczNmU5NmEzMjY2M2EwODc1NTdmMTI4OWVhMWVkNjBhNTE3NTQxM2NhNjBjODRiYSJ9fX0="),
    WOLF_SNOWY("WOLF", "entity.wolf.ambient", 
            "OGM4YWNmNDU1ZjY0ODMyYjZjOWRlYmIwM2EyYzI2MTZkNDI2ZmVhOTllY2E5MTA5OWI2MWZhZThiNmRiODg2OSJ9fX0="),
    WOLF_SNOWY_ANGRY("WOLF", "entity.wolf.ambient", 
            "MWMyOTg2ZjcxYzQ0Zjc3MGQxZmJiYjRjNWIzZWMyOWJlNzdlYTcyYWFhYzZiOTVlYzZkNmQ1MjBiZTZjOTM4YSJ9fX0="),
    WOLF_SPOTTED("WOLF", "entity.wolf.ambient", 
            "NjQzZTM0YzMwNjNkMWE1MzAxNmI2MmRhYTViYjE1YjcyMjllOWMwYjc3MjVlYTRlODk1Y2JhYmM1ZmE3ODQwMCJ9fX0="),
    WOLF_SPOTTED_ANGRY("WOLF", "entity.wolf.ambient", 
            "M2E0OWFiN2Q3ODk2ZDE3ZjlkNzU0ZmRlYWM4NWFlYWQ0YTVmNjQ5Y2ZmYTllZjNmOTEwMzU2N2UwMjQ5NWY3YSJ9fX0="),
    WOLF_STRIPED("WOLF", "entity.wolf.ambient", 
            "ZGNjZDBlMGRmZjkyYzA3OWY4NTlhYzVlOTAzNjkyMWI1MjBiNjhiYmQ4MmE4ZTY1ZWZjMzNkZjQ2NmUyZDk2YiJ9fX0="),
    WOLF_STRIPED_ANGRY("WOLF", "entity.wolf.ambient", 
            "YTQzMmQyMzU5OWQ1ODIwMzE0ZWFmMDRlNmVjZDg1YjQzMTI0ZmU0OTMzYWRkODk3MGUyMDRkYThjY2I1MTNiNiJ9fX0="),
    WOLF_WOODS("WOLF", "entity.wolf.ambient", 
            "MWY3MmJiODk5ODY5Yjc2ZTFhMmIwZDUxMzczNmI4ZDZiZGM1MTM4ZjM3NGE4NTc3ZTFjNWM3NmI3MmZkNDIxOCJ9fX0="),
    WOLF_WOODS_ANGRY("WOLF", "entity.wolf.ambient", 
            "YjZmNzcyNWYxZTkwZjE5ZmIyOTUzNjQ0NWM5YjhiZjc1MjNjNWU1YTc1OTQ1MGMyNzBmNjk0OGIxMGI0ZTI4ZiJ9fX0="),
    ZOGLIN("ZOGLIN", "entity.zoglin.ambient", 
            "M2M4YzdjNWQwNTU2Y2Q2NjI5NzE2ZTM5MTg4YjIxZTdjMDQ3NzQ3OWYyNDI1ODdiZjE5ZTBiYzc2YjMyMjU1MSJ9fX0="),
    ZOMBIE_HORSE("ZOMBIE_HORSE", "entity.zombie_horse.ambient", 
            "Zjg5NmExZGJkZTFhMTk1NDBjZTczMzZjNmM5NGY1OTY1MmFhOThiYjEwNjhiMmVmOGM4ZmE2ZWY4NTgwNGY1NyJ9fX0="),
    ZOMBIE_VILLAGER_NULL("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "ZTVlMDhhODc3NmMxNzY0YzNmZTZhNmRkZDQxMmRmY2I4N2Y0MTMzMWRhZDQ3OWFjOTZjMjFkZjRiZjNhYzg5YyJ9fX0="),
    ZOMBIE_VILLAGER_ARMORER("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "MzE3YWIxZjRhMzFiZTUyYTZjOTk1ZTI0MDg3OGYwMTgyNGNjOTA1NDM5ZDY2NDI1NjVkNjA5MWM2NDFhZjhlYSJ9fX0="),
    ZOMBIE_VILLAGER_BUTCHER("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "N2M4ZGNiZGVlOTgzZDI1NGY5NDQzNjcwZTJmN2JmNDY3OWNkMDk5MjMyYmZlNmVmNjkzYzRlMjRjY2I5YjY2ZCJ9fX0="),
    ZOMBIE_VILLAGER_CARTOGRAPHER("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "MTQwMzVhY2EyNmJlOTdiZTg0MDY0MDZmMTU1N2ZhOTkwNzM4NzcwZmUwMzgxOTRhNGFiODFjZTBjODM5NmM3MiJ9fX0="),
    ZOMBIE_VILLAGER_CLERIC("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "NTY4MDAxZjRmN2QwNzFiMjU0YmU3ZjMxMjA1MzYxYWU0ZmFiNjNjZTM4ODY0NzFhYTFjNzRlNjVmNjVlMWU2OSJ9fX0="),
    ZOMBIE_VILLAGER_FARMER("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "Zjc3ZDQxNWY5YmFhNGZhNGI1ZTA1OGY1YjgxYmY3ZjAwM2IwYTJjOTBhNDgzMWU1M2E3ZGJjMDk4NDFjNTUxMSJ9fX0="),
    ZOMBIE_VILLAGER_FISHERMAN("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "NjkwNWQ1M2ZlNGZhZWIwYjMxNWE2ODc4YzlhYjgxYjRiZTUyYzMxY2Q0NzhjMDI3ZjBkN2VjZTlmNmRhODkxNCJ9fX0="),
    ZOMBIE_VILLAGER_FLETCHER("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "MmVhMjZhYzBlMjU0OThhZGFkYTRlY2VhNThiYjRlNzZkYTMyZDVjYTJkZTMwN2VmZTVlNDIxOGZiN2M1ZWY4OSJ9fX0="),
    ZOMBIE_VILLAGER_LIBRARIAN("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "N2UzOGU4YWYwNzU3MDFhZDQwZGU1YjJlZjE4ZTFlZDM5Njc4ZTg1NTg0NDRlZTkxZDU2M2Q1ZTVhZWIzMmZhYiJ9fX0="),
    ZOMBIE_VILLAGER_SHEPHERD("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "NjkxMzkxYmVmM2E0NmVmMjY3ZDNiNzE3MTA4NmJhNGM4ZDE3ZjJhNmIwZjgzZmEyYWMzMGVmZTkxNGI3YzI0OSJ9fX0="),
    ZOMBIE_VILLAGER_WEAPONSMITH("ZOMBIE_VILLAGER", "zombie_villager.ambient", 
            "ZjM1NGE0MTcyYTliYTljNDdmYjg1M2FiMjg0ZmRjMGEzNDQzMjYwMTNlNWQ3M2M0YmVjNzgwMGQ4M2Y0ZTM5OSJ9fX0="),
    ZOMBIFIED_PIGLIN("ZOMBIFIED_PIGLIN", "zombified_piglin.ambient", 
            "N2VhYmFlY2M1ZmFlNWE4YTQ5Yzg4NjNmZjQ4MzFhYWEyODQxOThmMWEyMzk4ODkwYzc2NWUwYThkZTE4ZGE4YyJ9fX0="),
    GHAST("GHAST", "entity.ghast.ambient", 
            "OGI2YTcyMTM4ZDY5ZmJiZDJmZWEzZmEyNTFjYWJkODcxNTJlNGYxYzk3ZTVmOTg2YmY2ODU1NzFkYjNjYzAifX19"),
    VILLAGER_MASON("VILLAGER", "entity.villager.ambient", 
            "MmMwMmMzZmZkNTcwNWFiNDg4YjMwNWQ1N2ZmMDE2OGUyNmRlNzBmZDNmNzM5ZTgzOTY2MWFiOTQ3ZGZmMzdiMSJ9fX0="),
    VILLAGER_LEATHERWORKER("VILLAGER", "entity.villager.ambient", 
            "Zjc2Y2Y4YjczNzhlODg5Mzk1ZDUzOGU2MzU0YTE3YTNkZTZiMjk0YmI2YmY4ZGI5YzcwMTk1MWM2OGQzYzBlNiJ9fX0="),
    VILLAGER_TOOLSMITH("VILLAGER", "entity.villager.ambient", 
            "N2RmYTA3ZmQxMjQ0ZWI4OTQ1ZjRlZGVkZDAwNDI2NzUwYjc3ZWY1ZGZiYWYwM2VkNzc1NjMzNDU5ZWNlNDE1YSJ9fX0="),
    VILLAGER_NULL("VILLAGER", "entity.villager.ambient", 
            "ZDE0YmZmMWEzOGM5MTU0ZTVlYzg0Y2U1Y2YwMGM1ODc2OGUwNjhlYjQyYjJkODlhNmJiZDI5Nzg3NTkwMTA2YiJ9fX0="),
    VILLAGER_ARMORER("VILLAGER", "entity.villager.ambient", 
            "NmZjOWZiZTE0MjJkNWIwZWRiZTA2NTBlNTExYjFkOWMyMjkxNDYwNzUyYjA2NmM0ZjcwMWMwMjk3YTYyMDFlOCJ9fX0="),
    VILLAGER_BUTCHER("VILLAGER", "entity.villager.ambient", 
            "YzY3NzRkMmRmNTE1ZWNlYWU5ZWVkMjkxYzFiNDBmOTRhZGY3MWRmMGFiODFjNzE5MTQwMmUxYTQ1YjNhMjA4NyJ9fX0="),
    VILLAGER_CARTOGRAPHER("VILLAGER", "entity.villager.ambient", 
            "OTQyNDhkZDA2ODAzMDVhZDczYjIxNGU4YzZiMDAwOTRlMjdhNGRkZDgwMzQ2NzY5MjFmOTA1MTMwYjg1OGJkYiJ9fX0="),
    VILLAGER_CLERIC("VILLAGER", "entity.villager.ambient", 
            "ODZlN2E5MGJiNTM5MDhjMTljY2Y3OTVlNmVhNWMxOWQwOTdiMTlmMWYxMTFmYzJmMzBhNjFlNjg5ZGE4YTRmZCJ9fX0="),
    VILLAGER_FARMER("VILLAGER", "entity.villager.ambient", 
            "NTVhMGIwN2UzNmVhZmRlY2YwNTljOGNiMTM0YTdiZjBhMTY3ZjkwMDk2NmYxMDk5MjUyZDkwMzI3NjQ2MWNjZSJ9fX0="),
    VILLAGER_FISHERMAN("VILLAGER", "entity.villager.ambient", 
            "YWMxNWU1ZmI1NmZhMTZiMDc0N2IxYmNiMDUzMzVmNTVkMWZhMzE1NjFjMDgyYjVlMzY0M2RiNTU2NTQxMDg1MiJ9fX0="),
    VILLAGER_FLETCHER("VILLAGER", "entity.villager.ambient", 
            "MTc1MzJlOTBjNTczYTM5NGM3ODAyYWE0MTU4MzA1ODAyYjU5ZTY3ZjJhMmI3ZTNmZDAzNjNhYTZlYTQyYjg0MSJ9fX0="),
    VILLAGER_LIBRARIAN("VILLAGER", "entity.villager.ambient", 
            "ZTY2YTUzZmM3MDdjZTFmZjg4YTU3NmVmNDAyMDBjZThkNDlmYWU0YWNhZDFlM2IzNzg5YzdkMWNjMWNjNTQxYSJ9fX0="),
    VILLAGER_SHEPHERD("VILLAGER", "entity.villager.ambient", 
            "MTllMDRhNzUyNTk2ZjkzOWY1ODE5MzA0MTQ1NjFiMTc1NDU0ZDQ1YTA1MDY1MDFlN2QyNDg4Mjk1YTVkNWRlIn19fQ=="),
    VILLAGER_WEAPONSMITH("VILLAGER", "entity.villager.ambient", 
            "NWU0MDliOTU4YmM0ZmUwNDVlOTVkMzI1ZTZlOTdhNTMzMTM3ZTMzZmVjNzA0MmFjMDI3YjMwYmI2OTNhOWQ0MiJ9fX0="),
    PARROT_RED("PARROT", "entity.parrot.ambient", 
            "NWQxYTE2OGJjNzJjYjMxNGY3Yzg2ZmVlZjlkOWJjNzYxMjM2NTI0NGNlNjdmMGExMDRmY2UwNDIwMzQzMGMxZCJ9fX0="),
    PARROT_BLUE("PARROT", "entity.parrot.ambient", 
            "MjBlMDNiMTBjMTVlZTU2MDE0MjM4NjdkZmI4YmNiY2JjOTE5Y2E5NmMwZWVhNjMwNzNlYzhlNzk1ZWFiZDA1ZiJ9fX0="),
    PARROT_CYAN("PARROT", "entity.parrot.ambient", 
            "YmM2NDcxZjIzNTQ3YjJkYmRmNjAzNDdlYTEyOGY4ZWIyYmFhNmE3OWIwNDAxNzI0ZjIzYmQ0ZTI1NjRhMmI2MSJ9fX0="),
    PARROT_GRAY("PARROT", "entity.parrot.ambient", 
            "YTNjMzQ3MjJhYzY0NDk2YzliODRkMGM1NDAxOWRhYWU2MTg1ZDYwOTQ5OTAxMzNhZDY4MTBlZWEzZDI0MDY3YSJ9fX0="),
    PARROT_GREEN("PARROT", "entity.parrot.ambient", 
            "NWZjOWEzYjlkNTg3OWMyMTUwOTg0ZGJmZTU4OGNjMmU2MWZiMWRlMWU2MGZkMmE0NjlmNjlkZDRiNmY2YTk5MyJ9fX0="),
    ALLAY("ALLAY", "entity.allay.ambient_without_item",
            "YmVlYTg0NWNjMGI1OGZmNzYzZGVjZmZlMTFjZDFjODQ1YzVkMDljM2IwNGZlODBiMDY2M2RhNWM3YzY5OWViMyJ9fX0="),
    TADPOLE("TADPOLE", "tadpole.grow_up", 
            "YjIzZWJmMjZiN2E0NDFlMTBhODZmYjVjMmE1ZjNiNTE5MjU4YTVjNWRkZGQ2YTFhNzU1NDlmNTE3MzMyODE1YiJ9fX0="),
    WARDEN("WARDEN", "entity.warden.ambient", 
            "YzZmNzQzNjFmYjAwNDkwYTBhOThlZWI4MTQ1NDRlY2RkNzc1Y2I1NTYzM2RiYjExNGU2MGQyNzAwNGNiMTAyMCJ9fX0="),
    FROG_TEMPERATE("FROG", "entity.frog.ambient", 
            "MjNjZTZmOTk5OGVkMmRhNzU3ZDFlNjM3MmYwNGVmYTIwZTU3ZGZjMTdjM2EwNjQ3ODY1N2JiZGY1MWMyZjJhMiJ9fX0="),
    FROG_WARM("FROG", "entity.frog.ambient", 
            "Zjc3MzE0ZmEwMzhlYzMxMzU3ODQ1YTkzMjc0YjRkYzg4NDEyNDY4NjcyOGZmZTBkZWQ5YzM1NDY2YWNhMGFhYiJ9fX0="),
    FROG_COLD("FROG", "entity.frog.ambient", 
            "Y2U2MmU4YTA0OGQwNDBlYjA1MzNiYTI2YTg2NmNkOWMyZDA5MjhjOTMxYzUwYjQ0ODJhYzNhMzI2MWZhYjZmMCJ9fX0="),
    BREEZE("BREEZE", "entity.breeze.idle_ground", 
            "Y2Q2ZTYwMmY3NmY4MGMwNjU3YjVhZWQ2NGUyNjdlZWVhNzAyYjMxZTZkYWU4NjM0NmM4NTA2ZjI1MzVjZWQwMiJ9fX0="),
    ARMADILLO("ARMADILLO", "entity.armadillo.ambient", 
            "YzljMWU5NmNlOTg1NzI1ZTIyZWQ2Y2NmMGY0YzQ4MTBjNzI5YTI1MzhiOTdiZGEwNmZhZWIzYjkyNzk5Yzg3OCJ9fX0="),
    BOGGED("BOGGED", "entity.bogged.ambient", 
            "NDgzNDc0YTgxM2EwMzg5ZTUyZmM1YWViZDVlNjllMDlhNzI1NDE2NDI4ODE1M2IxM2JkMDU5NjNiZjIzOTYxMSJ9fX0="),
    CREAKING("CREAKING", "entity.creaking.activate", 
            "MTJmZmNlNDU2MWYzYjA3NjkwZjU4Y2Q2MmM2ZjJiNWY4Y2NjMjc2ZjQ0M2MyZDFkN2NmZGU0ODcwYTJiYWYwMyJ9fX0="),
    HAPPY_GHAST("HAPPY_GHAST", "entity.happy_ghast.ambient", 
            "ODI2OThhYTcyNzRlZTI0MWQzMTM2MmUyZmFhNDhjZmE3MzNkMjUwMTA1MTY1NjhkNDBmM2Y5NjcyNDdkYTExYiJ9fX0="),
    COPPER_GOLEM("COPPER_GOLEM", "entity.copper_golem.spawn", 
            "OTllMjRlOTRkYmU0MmUyMzBkODMyOTNhNzdkNjFmZjcxMDFhOGM2OGFiNjhiYmM2YTkzZjk2MzBmYjJmZGI0In19fQ=="),
    NAUTILUS("NAUTILUS", "entity.nautilus.ambient", 
            "YjUzZDYzZWIxNzViMDBmYjM1Mjg1ZjQzMzBkMGJlNjhhMDcxM2RiOTRlMDBlNmZkZDg1ODMyZDQxZTNhMDhiIn19fQ=="),
    PARCHED("PARCHED", "entity.parched.ambient", 
            "MjRhZWNlZmY1ZjI2ZGQ4NDEzYzVjMDM1NDdjMjM0YWMwMzEwOGQxODdhZjBiOWNkODM0YThjZTEyNTk4NTkxYyJ9fX0="),
    ZOMBIE_NAUTILUS("ZOMBIE_NAUTILUS", "entity.zombie_nautilus.ambient", 
            "ZmQ5YTkzMzM3NmRhNDRjMzM5MTMwN2NiOWY0Y2YwM2YxNmYzYTU0ZjQ5NWZkNWExMWJhZDhhMzczZjlkNTcyMCJ9fX0="),
    CAMEL_HUSK("CAMEL_HUSK", "entity.camel_husk.ambient", 
            "M2JkN2E5MmE2ZjY3Yjc1MDBkMTZjNGUxMmYyODA1OGVjMjg1OTMxMTU1NmJhMDNiZTJkMWY1ODExNzBmMmRiNiJ9fX0="),

    // AH sh, yeah nah I ain't doing 3072 variants

    TROPICAL_FISH_ORANGE("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                 "ZDZkZDVlNmFkZGI1NmFjYmM2OTRlYTRiYTU5MjNiMWIyNTY4ODE3OGZlZmZhNzIyOTAyOTllMjUwNWM5NzI4MSJ9fX0="),
    TROPICAL_FISH_MAGENTA("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                  "NzViYTM5M2I5MjZlZTY5YTE0ZDRkODUzYjI1ZDI4NWE4NjhiMTZjNTZjOTE5ZDJiODI0NDEzZTY1NjZkNGU1NSJ9fX0="),
    TROPICAL_FISH_LIGHT_BLUE("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                     "M2IwNDlhNjlhZDJiNGQ4YTVkYWFiODM3MmVlOTEyYzcyOGFjODA5ZjhmZDQxMGNiZTdhMGI4MDU0NmRlOThjYiJ9fX0="),
    TROPICAL_FISH_YELLOW("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                 "NWQ3YjkyYTFiZGM3MzNkMmE1M2ZiMDk1YzcwYjczMmI3MWEyMjNhOWNlY2E3MmI4NzJlMWVlOTkwYTZhOTA3ZSJ9fX0="),
    TROPICAL_FISH_PINK("TROPICAL_FISH", "entity.tropical_fish.ambient",
                               "NzViYTM5M2I5MjZlZTY5YTE0ZDRkODUzYjI1ZDI4NWE4NjhiMTZjNTZjOTE5ZDJiODI0NDEzZTY1NjZkNGU1NSJ9fX0="),
    TROPICAL_FISH_GRAY("TROPICAL_FISH", "entity.tropical_fish.ambient",
                               "ZmMwZDFlNmQyYTlkZjRmMGViYmNkNTQ3NzhmZjMxYjdjMjQ5ZTBkOTk0NGZjZWQ0YjFhODNhZmJhZWVhY2ZjYSJ9fX0="),
    TROPICAL_FISH_CYAN("TROPICAL_FISH", "entity.tropical_fish.ambient",
                               "M2IwNDlhNjlhZDJiNGQ4YTVkYWFiODM3MmVlOTEyYzcyOGFjODA5ZjhmZDQxMGNiZTdhMGI4MDU0NmRlOThjYiJ9fX0="),
    TROPICAL_FISH_BLUE("TROPICAL_FISH", "entity.tropical_fish.ambient",
                               "NGNjYWU0MzY2NWYxMjNhODRjZWUzN2Y1MGVlMjQxODc3ZTA1ZGJjZmEyODA5ZWM1OWFjNTdkMGNlZDZmZTc5OSJ9fX0="),
    TROPICAL_FISH_GREEN("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                "YWRmYjRkN2RmZjU0NTZkZTcwNDk2NDE0ZTg3NGM2NjUwYTFlODM5NTYzY2M3NWQ0Yjk5MzgwYjIxNmNmZGJjZCJ9fX0="),
    TROPICAL_FISH_RED("TROPICAL_FISH", "entity.tropical_fish.ambient",
                              "N2U5MmYwYjBmNzljN2JhOWRjODE1NzdiZTMzYTVjNzEzZmJlMzk3MjgyNmI0NGJjZjI2ZmViNmNjMTJiNjQzNCJ9fX0="),
    TROPICAL_FISH_BLACK("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                "MjNkODU3ZGFlN2IyYWNmM2JmZDk2NjZmMWVkZWFkZGY0YmExNjkyNTA1ZjBhOWFjYzFkYTc2YzgyOGU0MDU2NyJ9fX0="),
    TROPICAL_FISH_LIGHT_GRAY("TROPICAL_FISH", "entity.tropical_fish.ambient",
                                     "MjNkODU3ZGFlN2IyYWNmM2JmZDk2NjZmMWVkZWFkZGY0YmExNjkyNTA1ZjBhOWFjYzFkYTc2YzgyOGU0MDU2NyJ9fX0=");


    private final String name;
    private final String sound;
    private final String headskin;
    private final UUID headUUID;
    private static final String PREFIX = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv";

    final MainScript instance = MainScript.getInstance();

    private EntityHeadVariants(String name, String sound, String headSkinSuffix) {
        this.name = name;
        this.sound = sound;
        this.headskin = PREFIX + headSkinSuffix;
        this.headUUID = UUID.nameUUIDFromBytes(this.headskin.getBytes());
    }

    public PlayerProfile getSkullProfile() {
        try {
            UUID profileUuid = this.headUUID;
            String formattedName = this.name.substring(0, 1).toUpperCase() +
                    this.name.substring(1).toLowerCase().replace("_", "");

            PlayerProfile profile = Bukkit.createPlayerProfile(profileUuid, formattedName);
            PlayerTextures textures = profile.getTextures();

            String textureUrl = "http://textures.minecraft.net/texture/" +
                    extractTextureHash(this.headskin);
            textures.setSkin(new URL(textureUrl));

            profile.setTextures(textures);
            return profile;
        } catch (Exception e) {
            MainScript.getInstance().getLogger().warning(
                    "Failed to create profile for " + this.name + ": " + e.getMessage()
            );
            return null;
        }
    }
    private String extractTextureHash(String base64) {
        try {
            String decoded = new String(Base64.getDecoder().decode(base64));

            int urlStart = decoded.indexOf("\"url\":\"") + 7;
            int urlEnd = decoded.indexOf("\"", urlStart);
            String fullUrl = decoded.substring(urlStart, urlEnd);

            return fullUrl.substring(fullUrl.lastIndexOf('/') + 1);
        } catch (Exception e) {
            return null;
        }
    }

    public String getFormattedName() {
        String name = this.name.replace("_", " ").toLowerCase();
        return name.substring(0, 1).toUpperCase() + name.substring(1);
    }

    public boolean shouldDrop() {
        return MainScript.getInstance().getConfig()
                .getBoolean(this.name + ".Drop", true);
    }

    public String getName() {
        return this.name;
    }

    public String getHeadHash() {
        return this.headskin;
    }

    public String getSound() {
        return this.sound;
    }
}
